os: osx
branches:
  only:
    - develop
language: node_js
node_js: 8
sudo: false
cache:
  directories:
    - node_modules
script:
  - npm run build
after_success:
  - cd build
  - cp index.html 404.html
  - git add --all .
  - git commit --message "Automatically update from travis-ci"
  - git push --quiet --force  "https://${GH_TOKEN}@${GH_REF}" master:master
# Note: you should set Environment Variables here or 'Settings' on travis-ci.org
env:
  global:
    - GH_REF: github.com/temberature/temberature.github.io.git
